import {test,expect,type Page} from '@playwright/test'
import {completeLevel,createInitialProgress} from '../src/engine/progressEngine.ts'
import {PROGRESS_KEY} from '../src/storage/progressStorage.ts'
import {animalHome} from '../src/games/world3/animal-home/content.ts'
import {foodSort} from '../src/games/world3/food-sort/content.ts'
import {shapePuzzle} from '../src/games/world3/shape-puzzle/content.ts'

async function seedThrough(page:Page,last:number){let progress=createInitialProgress();for(let id=1;id<=last;id++){const result=completeLevel(progress,{levelId:id,score:1100,stars:3,coinsEarned:75});if(!result.ok)throw Error(result.error);progress=result.value}await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(value))},{key:PROGRESS_KEY,value:progress})}
async function answerRound(page:Page,id:number){if(id<=12){const label=await page.locator('.arithmetic-model').getAttribute('aria-label');const match=label!.match(/(\d+) (plus|minus) (\d+)/)!;const answer=match[2]==='plus'?+match[1]+ +match[3]:+match[1]- +match[3];await page.getByRole('button',{name:String(answer),exact:true}).click();return}const instruction=(await page.locator('.question-prompt h2').innerText()).trim().toLowerCase();const picture=id===15?(await page.locator('.puzzle-picture span').first().textContent())!.trim().toLowerCase():'';const game=id===13?animalHome:id===14?foodSort:shapePuzzle;const question=game.questions.find(item=>item.instruction.toLowerCase()===instruction&&(id!==15||(item.prompt as {picture:string}).picture.toLowerCase()===picture));if(!question)throw Error(`No content match for level ${id}: ${instruction} / ${picture}`);const label=question.choices.find(choice=>choice.id===question.correctAnswerId)!.label;await page.getByRole('button',{name:label,exact:true}).click()}
async function play(page:Page,id:number){await page.getByRole('button',{name:'Start',exact:true}).click();for(let round=1;round<=10;round++){await expect(page.getByText(`Round ${round} / 10`,{exact:true})).toBeVisible();await answerRound(page,id)}await expect(page.getByRole('heading',{name:'Level Complete!'})).toBeVisible()}

test('Cloud Kingdom completes Levels 11–15, rewards once and unlocks coming-soon Level 16',async({page})=>{await seedThrough(page,10);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});for(let id=11;id<=15;id++){await page.goto(`/wondersteps/#/play/${id}`);await play(page,id);await expect(page.getByRole('img',{name:'3 of 3 stars'})).toBeVisible();if(id<15)await expect(page.getByText(`Level ${id+1} Unlocked!`)).toBeVisible()}await expect(page.getByText('Cloud Kingdom complete! Star Galaxy unlocked!')).toBeVisible();let saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),PROGRESS_KEY);expect(saved.coins).toBe(1125);expect(saved.levels.slice(10,15).every((level:{completed:boolean})=>level.completed)).toBe(true);await page.getByRole('button',{name:'Replay Level'}).click();await play(page,15);saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),PROGRESS_KEY);expect(saved.coins).toBe(1125);await expect(page.getByText('Cloud Kingdom complete! Star Galaxy unlocked!')).toHaveCount(0);await page.goto('/wondersteps/#/play/16');await expect(page.getByText(/Missing Letter gameplay is coming/)).toBeVisible();expect(errors).toEqual([])})

test('Cloud routes remain guarded and wrong answers retry without advancing',async({page})=>{await seedThrough(page,10);for(const id of [12,15,16]){await page.goto(`/wondersteps/#/play/${id}`);await expect(page).toHaveURL(/#\/levels$/)}await page.goto('/wondersteps/#/play/11');await page.reload();let saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),PROGRESS_KEY);expect(saved.levels[10].attempts).toBe(0);await page.getByRole('button',{name:'Start',exact:true}).click();await page.getByRole('button',{name:'Hear question again'}).click();const correctLabel=await page.locator('.arithmetic-model').getAttribute('aria-label');const match=correctLabel!.match(/(\d+) plus (\d+)/)!;const answer=+match[1]+ +match[2];const wrong=page.locator('.answer-card').filter({has:page.locator('.number-choice')}).filter({hasNot:page.locator(`.number-choice:text-is("${answer}")`)}).first();await wrong.click();await expect(page.getByRole('status')).toContainText('Almost');await expect(page.getByText('Round 1 / 10',{exact:true})).toBeVisible();await page.getByRole('button',{name:String(answer),exact:true}).click();await expect(page.getByText('Round 2 / 10',{exact:true})).toBeVisible();saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),PROGRESS_KEY);expect(saved.levels[10].attempts).toBe(1)})

test('all Cloud games stay touch-sized and contained at target viewports',async({page})=>{await seedThrough(page,14);const sizes=[[320,568],[360,640],[375,667],[390,844],[414,896],[430,932],[480,800],[768,900],[1024,900],[1280,900],[1440,900],[1920,1080],[667,375],[740,360],[844,390]];for(const [width,height] of sizes){await page.setViewportSize({width,height});for(let id=11;id<=15;id++){await page.goto(`/wondersteps/#/play/${id}`);await page.getByRole('button',{name:'Start',exact:true}).click();await page.waitForTimeout(400);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}x${height} level ${id}`).toBe(true);const targets=await page.locator('.answer-card,.hear-again').evaluateAll(nodes=>nodes.map(node=>{const box=node.getBoundingClientRect();return {w:box.width,h:box.height,left:box.left,right:box.right}}));expect(targets.every(box=>box.w>=44&&box.h>=44&&box.left>=0&&box.right<=width),`${width}x${height} level ${id}`).toBe(true)}}})
