import {test,expect,type Page} from '@playwright/test'
import {completeLevel,createInitialProgress} from '../src/engine/progressEngine.ts'
import {PROGRESS_KEY} from '../src/storage/progressStorage.ts'
import {miniRounds} from '../src/games/world2/content.ts'

async function seedWorld2(page:Page){let progress=createInitialProgress();for(let id=1;id<=5;id++){const result=completeLevel(progress,{levelId:id,score:1100,stars:3,coinsEarned:75});if(!result.ok)throw Error(result.error);progress=result.value}await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(value))},{key:PROGRESS_KEY,value:progress})}
async function playShape(page:Page){await page.getByRole('button',{name:'Start',exact:true}).click();for(let round=1;round<=10;round++){await expect(page.getByText(`Round ${round} / 10`,{exact:true})).toBeVisible();const shape=(await page.locator('.question-prompt h2').innerText()).replace('Find the ','').replace('.','');await page.getByRole('button',{name:new RegExp('^'+shape+'$','i')}).click();if(round<10)await expect(page.getByText(`Round ${round+1} / 10`,{exact:true})).toBeVisible()}await expect(page.getByRole('heading',{name:'Level Complete!'})).toBeVisible()}
async function playMemory(page:Page){await page.getByRole('button',{name:'Start',exact:true}).click();for(const name of ['leaf','star','moon']){const cards=page.locator(`[data-symbol="${name}"]`);await cards.nth(0).click();await cards.nth(1).click();await page.waitForTimeout(550)}await expect(page.getByRole('heading',{name:'Level Complete!'})).toBeVisible()}
async function playHunt(page:Page){await page.getByRole('button',{name:'Start',exact:true}).click();for(let round=1;round<=10;round++){await expect(page.getByText(`Round ${round} / 10`,{exact:true})).toBeVisible();const target=(await page.locator('.world2-stage h2 strong').innerText()).trim();const buttons=page.getByRole('button',{name:new RegExp('^Letter '+target)});for(let n=0;n<3;n++)await buttons.filter({hasNotText:'✓'}).first().click();if(round<10)await expect(page.getByText(`Round ${round+1} / 10`,{exact:true})).toBeVisible()}await expect(page.getByRole('heading',{name:'Level Complete!'})).toBeVisible()}
async function playOrder(page:Page){await page.getByRole('button',{name:'Start',exact:true}).click();for(let round=1;round<=10;round++){await expect(page.getByText(`Round ${round} / 10`,{exact:true})).toBeVisible();const values=await page.locator('.number-grid button').evaluateAll(nodes=>nodes.map(n=>Number(n.textContent)).sort((a,b)=>a-b));for(const value of values)await page.getByRole('button',{name:'Number '+value,exact:true}).click();if(round<10)await expect(page.getByText(`Round ${round+1} / 10`,{exact:true})).toBeVisible()}await expect(page.getByRole('heading',{name:'Level Complete!'})).toBeVisible()}
async function playMini(page:Page){await page.getByRole('button',{name:'Start',exact:true}).click();for(let round=0;round<10;round++){await expect(page.getByText(`Round ${round+1} / 10`,{exact:true})).toBeVisible();await page.getByRole('button',{name:miniRounds[round].answer,exact:true}).click()}await expect(page.getByRole('heading',{name:'Level Complete!'})).toBeVisible()}
test('World 2 progresses through four distinct interactions and unlocks Cloud Kingdom',async({page})=>{await seedWorld2(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 const players=[playShape,playMemory,playHunt,playOrder,playMini];for(let id=6;id<=10;id++){await page.goto('/wondersteps/#/play/'+id);await players[id-6](page);await expect(page.getByRole('img',{name:'3 of 3 stars'})).toBeVisible();if(id<10){await expect(page.getByText(`Level ${id+1} Unlocked!`)).toBeVisible();await page.getByRole('link',{name:'Next Level'}).click()}}
 await expect(page.getByText('Cloud Kingdom unlocked!')).toBeVisible();let saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),PROGRESS_KEY);expect(saved.levels.slice(5,10).every((level:{completed:boolean})=>level.completed)).toBe(true);expect(saved.coins).toBe(750);await page.getByRole('button',{name:'Replay Level'}).click();await playMini(page);saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),PROGRESS_KEY);expect(saved.coins).toBe(750);await expect(page.getByText('Cloud Kingdom unlocked!')).toHaveCount(0);await page.goto('/wondersteps/#/play/11');await expect(page.getByRole('heading',{name:'Addition'})).toBeVisible();await expect(page.getByRole('button',{name:'Start',exact:true})).toBeVisible();expect(errors).toEqual([])})
test('World 2 guards, attempts, refresh, feedback, voice control and responsive targets remain safe',async({page})=>{await seedWorld2(page);await page.goto('/wondersteps/#/play/7');await expect(page).toHaveURL(/#\/levels$/);await page.goto('/wondersteps/#/play/10');await expect(page).toHaveURL(/#\/levels$/);await page.goto('/wondersteps/#/play/6');await page.reload();let saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),PROGRESS_KEY);expect(saved.levels[5].attempts).toBe(0);await page.getByRole('button',{name:'Start',exact:true}).click();await page.getByRole('button',{name:'Hear question again'}).click();const correct=(await page.locator('.question-prompt h2').innerText()).replace('Find the ','').replace('.','');const wrong=page.locator('.answer-card').filter({hasNot:page.locator(`.shape-${correct}`)}).first();await wrong.click();await expect(page.getByRole('status')).toContainText(/Almost|Try/);await page.reload();saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),PROGRESS_KEY);expect(saved.levels[5].attempts).toBe(1);await page.setViewportSize({width:320,height:568});await page.getByRole('button',{name:'Start',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const boxes=await page.locator('.answer-card,.hear-again').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().toJSON()));expect(boxes.every(b=>b.width>=44&&b.height>=44&&b.right<=320)).toBe(true)})
test('all World 2 interactions remain touch-sized without overflow across target viewports',async({page})=>{let progress=createInitialProgress();for(let id=1;id<=9;id++){const result=completeLevel(progress,{levelId:id,score:1100,stars:3,coinsEarned:75});if(!result.ok)throw Error(result.error);progress=result.value}await page.addInitScript(({key,value})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(value))},{key:PROGRESS_KEY,value:progress});const sizes=[[320,568],[360,640],[375,667],[390,844],[414,896],[430,932],[480,800],[768,900],[1024,900],[1280,900],[1440,900],[1920,1080],[667,375],[740,360],[844,390]];for(const [width,height] of sizes){await page.setViewportSize({width,height});for(let id=6;id<=10;id++){await page.goto('/wondersteps/#/play/'+id);await page.getByRole('button',{name:'Start',exact:true}).click();await page.waitForTimeout(400);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}x${height} level ${id}`).toBe(true);const targets=await page.locator('.answer-card,.memory-card,.letter-grid button,.number-grid button,.mini-grid button,.hear-again').evaluateAll(nodes=>nodes.map(n=>{const b=n.getBoundingClientRect();return {w:b.width,h:b.height,left:b.left,right:b.right}}));expect(targets.every(b=>b.w>=44&&b.h>=44&&b.left>=0&&b.right<=width),`${width}x${height} level ${id}`).toBe(true)}}})
