import { ArrowRight, ChevronRight, Cloud, Compass, Heart, Leaf, Play, Settings, Sparkles, Star, Sun, Trophy } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Mascot } from '../components/game/Mascot'
import { Badge, ButtonLink } from '../components/ui/Primitives'
export default function Home() {
return <div className="home"><div className="welcome-label"><span className="tiny-sun"><Sun size={17}/></span> A little wonder, every day</div>
<section className="hero"><div className="hero-copy"><Badge><Sparkles size={15}/> BIG ADVENTURES FOR LITTLE MINDS</Badge><h1>Small steps.<br/><span>Big discoveries.</span></h1><p>A world of colors, numbers, and happy little<br className="desktop-break"/> surprises. Let’s explore together!</p><div className="hero-actions"><ButtonLink to="/play/1"><Play size={22} fill="currentColor"/> Let’s play <ArrowRight size={20}/></ButtonLink><ButtonLink secondary to="/levels"><Compass size={21}/> Explore levels</ButtonLink></div><span className="hero-note"><Heart size={15}/> Made for curious minds, ages 4–8</span></div>
<div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><Cloud className="art-cloud cloud-one"/><Cloud className="art-cloud cloud-two"/><Star className="art-star star-one" fill="currentColor"/><Star className="art-star star-two" fill="currentColor"/><span className="art-dot dot-one"/><span className="art-dot dot-two"/><div className="mascot-stage"><Mascot/></div><span className="mascot-greeting">Hi, I’m Pip! <span aria-hidden="true">✦</span></span><Leaf className="art-leaf"/></div></section>
<section className="journey-preview" aria-labelledby="journey-title"><div className="section-heading"><div><span className="eyebrow">YOUR NEXT LITTLE STEP</span><h2 id="journey-title">A whole world of wonder</h2></div><Link className="text-link" to="/levels">See the map <ArrowRight size={17}/></Link></div><Link className="world-preview" to="/levels"><div className="meadow-illustration" aria-hidden="true"><Sun className="meadow-sun"/><div className="hill hill-back"/><div className="hill hill-front"/><span className="flower flower-one">✿</span><span className="flower flower-two">✿</span><span className="trail-dot trail-one"/><span className="trail-dot trail-two"/><span className="trail-dot trail-three"/></div><div className="world-preview-copy"><span className="eyebrow">WORLD 01 · LEVELS 1–5</span><h3>Sunny Meadow</h3><p>Every adventure starts with a little curiosity.</p><span className="world-start"><span/> Start with Color Match</span></div><span className="round-arrow"><ChevronRight size={24}/></span></Link></section>
<nav className="home-shortcuts" aria-label="More to explore"><Link to="/achievements"><span className="shortcut-icon trophy-bg"><Trophy/></span><span><strong>Little victories</strong><small>Your achievements live here</small></span><ChevronRight size={19}/></Link><Link to="/settings"><span className="shortcut-icon settings-bg"><Settings/></span><span><strong>Just your way</strong><small>Make yourself at home</small></span><ChevronRight size={19}/></Link></nav></div>
}

